#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    path = os.path.realpath(os.path.dirname(__file__))
    os.chdir(path)
    sys.path.insert(0, "src")
    from src.wgtool.cli import main  # fmt: skip
    main()
